FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*

COPY requirements-backend.txt .
RUN pip install --default-timeout=1000 --no-cache-dir -r requirements-backend.txt

COPY . .
RUN mkdir -p /app/static

EXPOSE 8000
CMD ["python", "server.py"]